apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetlogdemo
spec:
  selector:
    matchLabels:
      app: dotnetlogdemo
  template:
    metadata:
      labels:
        app: dotnetlogdemo
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: dotnetlogdemo
        ports:
        - containerPort: 6100
        env:
        - name: PORT
          value: "6100"
        - name: HOSTNAME
          value: "*"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 1
          httpGet:
            path: /
            port: 6100

